### PR TITLE
load font from url

### PR DESCRIPTION
**Pull request by hipstersmoothie**
enables node program to load font from url

@mattdesl

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
@mattdesl do you need me to add anything to this?

**Comment by hipstersmoothie** [comment]
@mattdesl ping

**Comment by mattdesl** [comment]
Thanks! Publishing

**Comment by mattdesl** [comment]
Hmm for some reason I can't publish to npm right now... not sure what's up

**Comment by mattdesl** [comment]
Ok, published to 1.4.0

**Pull request merged**
